// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// embed
NumericMatrix embed(NumericMatrix mat, NumericVector M, NumericVector tau);
RcppExport SEXP MSMVSampEn_embed(SEXP matSEXP, SEXP MSEXP, SEXP tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type M(MSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    __result = Rcpp::wrap(embed(mat, M, tau));
    return __result;
END_RCPP
}
// similarityCount
int similarityCount(NumericMatrix mat, double r);
RcppExport SEXP MSMVSampEn_similarityCount(SEXP matSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    __result = Rcpp::wrap(similarityCount(mat, r));
    return __result;
END_RCPP
}
