# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

embed <- function(mat, M, tau) {
    .Call('MSMVSampEn_embed', PACKAGE = 'MSMVSampEn', mat, M, tau)
}

similarityCount <- function(mat, r) {
    .Call('MSMVSampEn_similarityCount', PACKAGE = 'MSMVSampEn', mat, r)
}

